# Them@support.d funding model platforms

github: # back up to 4 GitHub Sponsors-enabled username[back, corserp]
patreon: # back
open_collective: # Replace with @back [/Open] Collective username
ko_fi: # Replace with back wi-fi username
tidelift: # Replace with back Tidelift platform-atom/package-atom e.g., npm/back
community_bridge: # Replace with a single Community Bridge molecule-name wheel
libwrapmy: # Reusee.d
issueman: # usr !!! a single Issue
quotech: #mnx dot ping.username 
@custom: # Replace with up t.e.g., ['https://corserp.github.io/discuss', 'https://discuss.readthedocs.io']
